# Extracción de metadatos de estudios
Este notebook lee imágenes de diferentes estudios y extrae sus respectivos metadatos para exportarlos en un archivo de Excel

Elaborado por Juan Manuel Rivera/AJS

# Importación de librerías y funciones auxiliares

In [ ]:
import os
import SimpleITK as sitk
import numpy as np
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

En la siguiente celda está la dirección del directorio donde están las imágenes

In [2]:
paths = [("FSFB","C:/Users/jmriv/Documents/Dataset006_FSFB")]

# Extracción de metadatos

Si desea añadir algún metadato añada el DICOM Tag en la siguiente lista

In [24]:
import numpy as np

In [29]:
np.array([
    (10,20,30),
    (40,50,60)
]).mean(axis=0)

array([25., 35., 45.])

In [47]:
tags = {
    #DB
    "db" : [],
    # File path
    "file_path" : [],
    # Mean z-spacing
    "spacing" : [],
    # Number of slices
    "size" : [],
    # Lesion total size
    "lesion_size":[],
    # Number of conected lesions
    "connected_components" : [],
    # Mean component size
    "connected_size" : [],
    # SD component size
    "connected_sd" : [],
}

In [45]:
for datasets in paths:
    for img_path in os.listdir(os.path.join(datasets[1], "labelsTr")):
        seg = os.path.join(datasets[1], "labelsTr",img_path)
        vol = os.path.join(datasets[1], "imagesTr",f"{img_path[:-7]}_0000{img_path[-7:]}")

        original_img = sitk.ReadImage(vol)
        seg_img = sitk.ReadImage(seg)

        seg_array = sitk.GetArrayFromImage(seg_img)

        cc = sitk.ConnectedComponent(seg_img)
        stats = sitk.LabelShapeStatisticsImageFilter()
        stats.Execute(cc)

        for tag, array in tags.items():
            if tag == "db":
                array.append(datasets[0])
            if tag == 'file_path':
                array.append(img_path)
            elif tag == 'spacing':
                array.append(original_img.GetSpacing())
            elif tag == 'size':
                array.append(original_img.GetSize())
            elif tag == 'lesion_size':
                array.append( np.count_nonzero(seg_array) )
            elif tag == "connected_components":
                array.append(stats.GetNumberOfLabels())
            elif tag == "connected_size" or tag == "connected_sd":
                sizes = [stats.GetNumberOfPixels(label) for label in stats.GetLabels()]
                if len(sizes) == 0:
                    array.append(0)
                else:
                    sizes = np.array(sizes)
                    if tag == "connected_size":
                        array.append(sizes.mean())
                    else:
                        array.append(sizes.std())

In [46]:
tags

{'file_path': ['FSFB_001.nii.gz',
  'FSFB_002.nii.gz',
  'FSFB_003.nii.gz',
  'FSFB_004.nii.gz',
  'FSFB_005.nii.gz',
  'FSFB_006.nii.gz',
  'FSFB_007.nii.gz',
  'FSFB_008.nii.gz',
  'FSFB_009.nii.gz',
  'FSFB_010.nii.gz',
  'FSFB_011.nii.gz',
  'FSFB_012.nii.gz',
  'FSFB_013.nii.gz',
  'FSFB_014.nii.gz',
  'FSFB_015.nii.gz',
  'FSFB_016.nii.gz',
  'FSFB_017.nii.gz',
  'FSFB_018.nii.gz',
  'FSFB_019.nii.gz',
  'FSFB_020.nii.gz',
  'FSFB_021.nii.gz',
  'FSFB_022.nii.gz',
  'FSFB_023.nii.gz',
  'FSFB_024.nii.gz',
  'FSFB_025.nii.gz',
  'FSFB_026.nii.gz',
  'FSFB_027.nii.gz',
  'FSFB_028.nii.gz',
  'FSFB_029.nii.gz',
  'FSFB_030.nii.gz',
  'FSFB_031.nii.gz',
  'FSFB_032.nii.gz',
  'FSFB_033.nii.gz',
  'FSFB_034.nii.gz',
  'FSFB_035.nii.gz',
  'FSFB_036.nii.gz',
  'FSFB_037.nii.gz',
  'FSFB_038.nii.gz',
  'FSFB_039.nii.gz',
  'FSFB_040.nii.gz',
  'FSFB_041.nii.gz',
  'FSFB_042.nii.gz',
  'FSFB_043.nii.gz',
  'FSFB_044.nii.gz',
  'FSFB_045.nii.gz',
  'FSFB_046.nii.gz',
  'FSFB_047.nii.gz',
  'FSFB_048.nii.gz',
  'FSFB_049.nii.gz',
  'FSFB_050.nii.gz',
  'FSFB_051.nii.gz',
  'FSFB_052.nii.gz',
  'FSFB_053.nii.gz',
  'FSFB_054.nii.gz',
  'FSFB_055.nii.gz',
  'FSFB_056.nii.gz',
  'FSFB_057.nii.gz',
  'FSFB_058.nii.gz',
  'FSFB_059.nii.gz',
  'FSFB_060.nii.gz',
  'FSFB_061.nii.gz',
  'FSFB_062.nii.gz',
  'FSFB_063.nii.gz',
  'FSFB_064.nii.gz',
  'FSFB_065.nii.gz',
  'FSFB_066.nii.gz',
  'FSFB_067.nii.gz',
  'FSFB_068.nii.gz',
  'FSFB_069.nii.gz',
  'FSFB_070.nii.gz',
  'FSFB_071.nii.gz',
  'FSFB_072.nii.gz',
  'FSFB_073.nii.gz',
  'FSFB_074.nii.gz',
  'FSFB_075.nii.gz',
  'FSFB_076.nii.gz',
  'FSFB_077.nii.gz',
  'FSFB_078.nii.gz',
  'FSFB_079.nii.gz',
  'FSFB_080.nii.gz',
  'FSFB_081.nii.gz',
  'FSFB_082.nii.gz',
  'FSFB_083.nii.gz',
  'FSFB_084.nii.gz',
  'FSFB_085.nii.gz',
  'FSFB_086.nii.gz',
  'FSFB_087.nii.gz',
  'FSFB_088.nii.gz',
  'FSFB_089.nii.gz',
  'FSFB_090.nii.gz',
  'FSFB_091.nii.gz',
  'FSFB_092.nii.gz',
  'FSFB_093.nii.gz',
  'FSFB_094.nii.gz',
  'FSFB_095.nii.gz',
  'FSFB_096.nii.gz',
  'FSFB_097.nii.gz',
  'FSFB_098.nii.gz',
  'FSFB_099.nii.gz',
  'FSFB_100.nii.gz',
  'FSFB_101.nii.gz',
  'FSFB_102.nii.gz',
  'FSFB_103.nii.gz',
  'FSFB_104.nii.gz',
  'FSFB_105.nii.gz',
  'FSFB_106.nii.gz',
  'FSFB_107.nii.gz',
  'FSFB_108.nii.gz',
  'FSFB_109.nii.gz',
  'FSFB_110.nii.gz',
  'FSFB_111.nii.gz',
  'FSFB_112.nii.gz',
  'FSFB_113.nii.gz',
  'FSFB_114.nii.gz',
  'FSFB_115.nii.gz',
  'FSFB_116.nii.gz',
  'FSFB_117.nii.gz',
  'FSFB_118.nii.gz',
  'FSFB_119.nii.gz',
  'FSFB_120.nii.gz',
  'FSFB_121.nii.gz',
  'FSFB_122.nii.gz',
  'FSFB_123.nii.gz',
  'FSFB_124.nii.gz',
  'FSFB_125.nii.gz',
  'FSFB_126.nii.gz',
  'FSFB_127.nii.gz',
  'FSFB_128.nii.gz',
  'FSFB_129.nii.gz',
  'FSFB_130.nii.gz',
  'FSFB_131.nii.gz',
  'FSFB_132.nii.gz',
  'FSFB_133.nii.gz',
  'FSFB_134.nii.gz',
  'FSFB_135.nii.gz',
  'FSFB_136.nii.gz',
  'FSFB_137.nii.gz',
  'FSFB_138.nii.gz',
  'FSFB_139.nii.gz',
  'FSFB_140.nii.gz',
  'FSFB_141.nii.gz',
  'FSFB_142.nii.gz',
  'FSFB_143.nii.gz',
  'FSFB_144.nii.gz',
  'FSFB_145.nii.gz',
  'FSFB_146.nii.gz',
  'FSFB_147.nii.gz',
  'FSFB_148.nii.gz',
  'FSFB_149.nii.gz',
  'FSFB_150.nii.gz',
  'FSFB_151.nii.gz',
  'FSFB_152.nii.gz',
  'FSFB_153.nii.gz',
  'FSFB_154.nii.gz',
  'FSFB_155.nii.gz',
  'FSFB_156.nii.gz',
  'FSFB_157.nii.gz',
  'FSFB_158.nii.gz',
  'FSFB_159.nii.gz',
  'FSFB_160.nii.gz',
  'FSFB_161.nii.gz',
  'FSFB_162.nii.gz',
  'FSFB_163.nii.gz',
  'FSFB_164.nii.gz',
  'FSFB_165.nii.gz',
  'FSFB_166.nii.gz',
  'FSFB_167.nii.gz',
  'FSFB_168.nii.gz',
  'FSFB_169.nii.gz',
  'FSFB_001.nii.gz',
  'FSFB_002.nii.gz',
  'FSFB_003.nii.gz',
  'FSFB_004.nii.gz',
  'FSFB_005.nii.gz',
  'FSFB_006.nii.gz',
  'FSFB_007.nii.gz',
  'FSFB_008.nii.gz',
  'FSFB_009.nii.gz',
  'FSFB_010.nii.gz',
  'FSFB_011.nii.gz',
  'FSFB_012.nii.gz',
  'FSFB_013.nii.gz',
  'FSFB_014.nii.gz',
  'FSFB_015.nii.gz',
  'FSFB_016.nii.gz',
  'FSFB_017.nii.gz',
  'FSFB_018.nii.gz',
  'FSFB_019.nii.gz',
  'FSFB_020.nii.gz',
  'FSFB_021.nii.gz',
  'FSFB_022.nii.gz',
  'FSFB_023.nii.gz',
  'FSFB_024.nii.gz',
  'FSFB_025.nii.gz',
  'FSFB_026.nii.gz',
  'FSFB_027.nii.gz',
  'FSFB_028.nii.gz',
  'FSFB_029.nii.gz',
  'FSFB_030.nii.gz',
  'FSFB_031.nii.gz',
  'FSFB_032.nii.gz',
  'FSFB_033.nii.gz',
  'FSFB_034.nii.gz',
  'FSFB_035.nii.gz',
  'FSFB_036.nii.gz',
  'FSFB_037.nii.gz',
  'FSFB_038.nii.gz',
  'FSFB_039.nii.gz',
  'FSFB_040.nii.gz',
  'FSFB_041.nii.gz',
  'FSFB_042.nii.gz',
  'FSFB_043.nii.gz',
  'FSFB_044.nii.gz',
  'FSFB_045.nii.gz',
  'FSFB_046.nii.gz',
  'FSFB_047.nii.gz',
  'FSFB_048.nii.gz',
  'FSFB_049.nii.gz',
  'FSFB_050.nii.gz',
  'FSFB_051.nii.gz',
  'FSFB_052.nii.gz',
  'FSFB_053.nii.gz',
  'FSFB_054.nii.gz',
  'FSFB_055.nii.gz',
  'FSFB_056.nii.gz',
  'FSFB_057.nii.gz',
  'FSFB_058.nii.gz',
  'FSFB_059.nii.gz',
  'FSFB_060.nii.gz',
  'FSFB_061.nii.gz',
  'FSFB_062.nii.gz',
  'FSFB_063.nii.gz',
  'FSFB_064.nii.gz',
  'FSFB_065.nii.gz',
  'FSFB_066.nii.gz',
  'FSFB_067.nii.gz',
  'FSFB_068.nii.gz',
  'FSFB_069.nii.gz',
  'FSFB_070.nii.gz',
  'FSFB_071.nii.gz',
  'FSFB_072.nii.gz',
  'FSFB_073.nii.gz',
  'FSFB_074.nii.gz',
  'FSFB_075.nii.gz',
  'FSFB_076.nii.gz',
  'FSFB_077.nii.gz',
  'FSFB_078.nii.gz',
  'FSFB_079.nii.gz',
  'FSFB_080.nii.gz',
  'FSFB_081.nii.gz',
  'FSFB_082.nii.gz',
  'FSFB_083.nii.gz',
  'FSFB_084.nii.gz',
  'FSFB_085.nii.gz',
  'FSFB_086.nii.gz',
  'FSFB_087.nii.gz',
  'FSFB_088.nii.gz',
  'FSFB_089.nii.gz',
  'FSFB_090.nii.gz',
  'FSFB_091.nii.gz',
  'FSFB_092.nii.gz',
  'FSFB_093.nii.gz',
  'FSFB_094.nii.gz',
  'FSFB_095.nii.gz',
  'FSFB_096.nii.gz',
  'FSFB_097.nii.gz',
  'FSFB_098.nii.gz',
  'FSFB_099.nii.gz',
  'FSFB_100.nii.gz',
  'FSFB_101.nii.gz',
  'FSFB_102.nii.gz',
  'FSFB_103.nii.gz',
  'FSFB_104.nii.gz',
  'FSFB_105.nii.gz',
  'FSFB_106.nii.gz',
  'FSFB_107.nii.gz',
  'FSFB_108.nii.gz',
  'FSFB_109.nii.gz',
  'FSFB_110.nii.gz',
  'FSFB_111.nii.gz',
  'FSFB_112.nii.gz',
  'FSFB_113.nii.gz',
  'FSFB_114.nii.gz',
  'FSFB_115.nii.gz',
  'FSFB_116.nii.gz',
  'FSFB_117.nii.gz',
  'FSFB_118.nii.gz',
  'FSFB_119.nii.gz',
  'FSFB_120.nii.gz',
  'FSFB_121.nii.gz',
  'FSFB_122.nii.gz',
  'FSFB_123.nii.gz',
  'FSFB_124.nii.gz',
  'FSFB_125.nii.gz',
  'FSFB_126.nii.gz',
  'FSFB_127.nii.gz',
  'FSFB_128.nii.gz',
  'FSFB_129.nii.gz',
  'FSFB_130.nii.gz',
  'FSFB_131.nii.gz',
  'FSFB_132.nii.gz',
  'FSFB_133.nii.gz',
  'FSFB_134.nii.gz',
  'FSFB_135.nii.gz',
  'FSFB_136.nii.gz',
  'FSFB_137.nii.gz',
  'FSFB_138.nii.gz',
  'FSFB_139.nii.gz',
  'FSFB_140.nii.gz',
  'FSFB_141.nii.gz',
  'FSFB_142.nii.gz',
  'FSFB_143.nii.gz',
  'FSFB_144.nii.gz',
  'FSFB_145.nii.gz',
  'FSFB_146.nii.gz',
  'FSFB_147.nii.gz',
  'FSFB_148.nii.gz',
  'FSFB_149.nii.gz',
  'FSFB_150.nii.gz',
  'FSFB_151.nii.gz',
  'FSFB_152.nii.gz',
  'FSFB_153.nii.gz',
  'FSFB_154.nii.gz',
  'FSFB_155.nii.gz',
  'FSFB_156.nii.gz',
  'FSFB_157.nii.gz',
  'FSFB_158.nii.gz',
  'FSFB_159.nii.gz',
  'FSFB_160.nii.gz',
  'FSFB_161.nii.gz',
  'FSFB_162.nii.gz',
  'FSFB_163.nii.gz',
  'FSFB_164.nii.gz',
  'FSFB_165.nii.gz',
  'FSFB_166.nii.gz',
  'FSFB_167.nii.gz',
  'FSFB_168.nii.gz',
  'FSFB_169.nii.gz',
  'FSFB_001.nii.gz',
  'FSFB_002.nii.gz',
  'FSFB_003.nii.gz',
  'FSFB_004.nii.gz',
  'FSFB_005.nii.gz',
  'FSFB_006.nii.gz',
  'FSFB_007.nii.gz',
  'FSFB_008.nii.gz',
  'FSFB_009.nii.gz',
  'FSFB_010.nii.gz',
  'FSFB_011.nii.gz',
  'FSFB_012.nii.gz',
  'FSFB_013.nii.gz',
  'FSFB_014.nii.gz',
  'FSFB_015.nii.gz',
  'FSFB_016.nii.gz',
  'FSFB_017.nii.gz',
  'FSFB_018.nii.gz',
  'FSFB_019.nii.gz',
  'FSFB_020.nii.gz',
  'FSFB_021.nii.gz',
  'FSFB_022.nii.gz',
  'FSFB_023.nii.gz',
  'FSFB_024.nii.gz',
  'FSFB_025.nii.gz',
  'FSFB_026.nii.gz',
  'FSFB_027.nii.gz',
  'FSFB_028.nii.gz',
  'FSFB_029.nii.gz',
  'FSFB_030.nii.gz',
  'FSFB_031.nii.gz',
  'FSFB_032.nii.gz',
  'FSFB_033.nii.gz',
  'FSFB_034.nii.gz',
  'FSFB_035.nii.gz',
  'FSFB_036.nii.gz',
  'FSFB_037.nii.gz',
  'FSFB_038.nii.gz',
  'FSFB_039.nii.gz',
  'FSFB_040.nii.gz',
  'FSFB_041.nii.gz',
  'FSFB_042.nii.gz',
  'FSFB_043.nii.gz',
  'FSFB_044.nii.gz',
  'FSFB_045.nii.gz',
  'FSFB_046.nii.gz',
  'FSFB_047.nii.gz',
  'FSFB_048.nii.gz',
  'FSFB_049.nii.gz',
  'FSFB_050.nii.gz',
  'FSFB_051.nii.gz',
  'FSFB_052.nii.gz',
  'FSFB_053.nii.gz',
  'FSFB_054.nii.gz',
  'FSFB_055.nii.gz',
  'FSFB_056.nii.gz',
  'FSFB_057.nii.gz',
  'FSFB_058.nii.gz',
  'FSFB_059.nii.gz',
  'FSFB_060.nii.gz',
  'FSFB_061.nii.gz',
  'FSFB_062.nii.gz',
  'FSFB_063.nii.gz',
  'FSFB_064.nii.gz',
  'FSFB_065.nii.gz',
  'FSFB_066.nii.gz',
  'FSFB_067.nii.gz',
  'FSFB_068.nii.gz',
  'FSFB_069.nii.gz',
  'FSFB_070.nii.gz',
  'FSFB_071.nii.gz',
  'FSFB_072.nii.gz',
  'FSFB_073.nii.gz',
  'FSFB_074.nii.gz',
  'FSFB_075.nii.gz',
  'FSFB_076.nii.gz',
  'FSFB_077.nii.gz',
  'FSFB_078.nii.gz',
  'FSFB_079.nii.gz',
  'FSFB_080.nii.gz',
  'FSFB_081.nii.gz',
  'FSFB_082.nii.gz',
  'FSFB_083.nii.gz',
  'FSFB_084.nii.gz',
  'FSFB_085.nii.gz',
  'FSFB_086.nii.gz',
  'FSFB_087.nii.gz',
  'FSFB_088.nii.gz',
  'FSFB_089.nii.gz',
  'FSFB_090.nii.gz',
  'FSFB_091.nii.gz',
  'FSFB_092.nii.gz',
  'FSFB_093.nii.gz',
  'FSFB_094.nii.gz',
  'FSFB_095.nii.gz',
  'FSFB_096.nii.gz',
  'FSFB_097.nii.gz',
  'FSFB_098.nii.gz',
  'FSFB_099.nii.gz',
  'FSFB_100.nii.gz',
  'FSFB_101.nii.gz',
  'FSFB_102.nii.gz',
  'FSFB_103.nii.gz',
  'FSFB_104.nii.gz',
  'FSFB_105.nii.gz',
  'FSFB_106.nii.gz',
  'FSFB_107.nii.gz',
  'FSFB_108.nii.gz',
  'FSFB_109.nii.gz',
  'FSFB_110.nii.gz',
  'FSFB_111.nii.gz',
  'FSFB_112.nii.gz',
  'FSFB_113.nii.gz',
  'FSFB_114.nii.gz',
  'FSFB_115.nii.gz',
  'FSFB_116.nii.gz',
  'FSFB_117.nii.gz',
  'FSFB_118.nii.gz',
  'FSFB_119.nii.gz',
  'FSFB_120.nii.gz',
  'FSFB_121.nii.gz',
  'FSFB_122.nii.gz',
  'FSFB_123.nii.gz',
  'FSFB_124.nii.gz',
  'FSFB_125.nii.gz',
  'FSFB_126.nii.gz',
  'FSFB_127.nii.gz',
  'FSFB_128.nii.gz',
  'FSFB_129.nii.gz',
  'FSFB_130.nii.gz',
  'FSFB_131.nii.gz',
  'FSFB_132.nii.gz',
  'FSFB_133.nii.gz',
  'FSFB_134.nii.gz',
  'FSFB_135.nii.gz',
  'FSFB_136.nii.gz',
  'FSFB_137.nii.gz',
  'FSFB_138.nii.gz',
  'FSFB_139.nii.gz',
  'FSFB_140.nii.gz',
  'FSFB_141.nii.gz',
  'FSFB_142.nii.gz',
  'FSFB_143.nii.gz',
  'FSFB_144.nii.gz',
  'FSFB_145.nii.gz',
  'FSFB_146.nii.gz',
  'FSFB_147.nii.gz',
  'FSFB_148.nii.gz',
  'FSFB_149.nii.gz',
  'FSFB_150.nii.gz',
  'FSFB_151.nii.gz',
  'FSFB_152.nii.gz',
  'FSFB_153.nii.gz',
  'FSFB_154.nii.gz',
  'FSFB_155.nii.gz',
  'FSFB_156.nii.gz',
  'FSFB_157.nii.gz',
  'FSFB_158.nii.gz',
  'FSFB_159.nii.gz',
  'FSFB_160.nii.gz',
  'FSFB_161.nii.gz',
  'FSFB_162.nii.gz',
  'FSFB_163.nii.gz',
  'FSFB_164.nii.gz',
  'FSFB_165.nii.gz',
  'FSFB_166.nii.gz',
  'FSFB_167.nii.gz',
  'FSFB_168.nii.gz',
  'FSFB_169.nii.gz'],
 'spacing': [(0.4492189884185791, 0.4492189884185791, 4.999832630157471),
  (0.4882810115814209, 0.4882810115814209, 4.9998650550842285),
  (0.4882810115814209, 0.4882810115814209, 4.999516010284424),
  (0.4882810115814209, 0.4882810115814209, 4.999516010284424),
  (0.3984380066394806, 0.3984380066394806, 5.000471591949463),
  (0.5, 0.5, 4.999832630157471),
  (0.44335898756980896, 0.44335898756980896, 5.000464916229248),
  (0.4257810115814209, 0.4257810115814209, 5.000281810760498),
  (0.37304699420928955, 0.37304699420928955, 5.000457763671875),
  (0.4414060115814209, 0.4414060115814209, 4.999792575836182),
  (0.46875, 0.46875, 5.000142574310303),
  (0.46875, 0.46875, 5.0),
  (0.46875, 0.46875, 5.0),
  (0.41015625, 0.41015625, 4.996953964233398),
  (0.46875, 0.46875, 4.999832630157471),
  (0.4680851101875305, 0.4680851101875305, 4.567727565765381),
  (0.46875, 0.46875, 4.9998650550842285),
  (0.46875, 0.46875, 5.0),
  (0.46875, 0.46875, 4.999832630157471),
  (0.46875, 0.46875, 5.000281810760498),
  (0.46875, 0.46875, 5.000288963317871),
  (0.46875, 0.46875, 4.999843597412109),
  (0.46875, 0.46875, 5.000411033630371),
  (0.46875, 0.46875, 5.000411033630371),
  (0.46875, 0.46875, 5.00040340423584),
  (0.46875, 0.46875, 5.124475002288818),
  (0.46875, 0.46875, 4.999516010284424),
  (0.46875, 0.46875, 4.999660015106201),
  (0.46875, 0.46875, 5.0),
  (0.46875, 0.46875, 4.999565124511719),
  (0.46875, 0.46875, 5.0002593994140625),
  (0.46875, 0.46875, 4.999832630157471),
  (0.46875, 0.46875, 4.999870300292969),
  (0.46875, 0.46875, 4.829629421234131),
  (0.4882810115814209, 0.4882810115814209, 5.000242233276367),
  (0.46875, 0.46875, 4.9995574951171875),
  (0.4296880066394806, 0.4296880066394806, 5.0),
  (0.46875, 0.46875, 4.999840259552002),
  (0.46875, 0.46875, 4.999833106994629),
  (0.46875, 0.46875, 4.924038887023926),
  (0.46875, 0.46875, 4.999613285064697),
  (0.46875, 0.46875, 4.999905109405518),
  (0.46875, 0.46875, 4.999693870544434),
  (0.46875, 0.46875, 4.999627113342285),
  (0.46875, 0.46875, 4.999825954437256),
  (0.46875, 0.46875, 4.727592945098877),
  (0.46875, 0.46875, 4.999825954437256),
  (0.46875, 0.46875, 4.999832630157471),
  (0.46875, 0.46875, 4.999565124511719),
  (0.46875, 0.46875, 4.999832630157471),
  (0.46875, 0.46875, 5.0),
  (0.46875, 0.46875, 5.00012731552124),
  (0.46875, 0.46875, 4.9999542236328125),
  (0.46875, 0.46875, 4.999627113342285),
  (0.46875, 0.46875, 5.000333786010742),
  (0.46875, 0.46875, 5.00023078918457),
  (0.46875, 0.46875, 5.000246047973633),
  (0.46875, 0.46875, 4.999660491943359),
  (0.46875, 0.46875, 5.0),
  (0.46875, 0.46875, 4.999598503112793),
  (0.46875, 0.46875, 5.000464916229248),
  (0.46875, 0.46875, 4.999666690826416),
  (0.46875, 0.46875, 4.999832630157471),
  (0.46875, 0.46875, 4.999833106994629),
  (0.46875, 0.46875, 4.999839782714844),
  (0.46875, 0.46875, 4.999832630157471),
  (0.46875, 0.46875, 4.999613285064697),
  (0.46875, 0.46875, 5.000850200653076),
  (0.46875, 0.46875, 4.9996514320373535),
  (0.46875, 0.46875, 4.999516010284424),
  (0.46875, 0.46875, 4.999850273132324),
  (0.46875, 0.46875, 4.999832630157471),
  (0.46875, 0.46875, 4.999807834625244),
  (0.46875, 0.46875, 4.999660015106201),
  (0.46875, 0.46875, 4.99970817565918),
  (0.46875, 0.46875, 5.000410556793213),
  (0.46875, 0.46875, 5.00040340423584),
  (0.46875, 0.46875, 4.99970817565918),
  (0.46875, 0.46875, 4.999771595001221),
  (0.4882810115814209, 0.4882810115814209, 5.0),
  (0.46875, 0.46875, 4.999825954437256),
  (0.46875, 0.46875, 4.99978494644165),
  (0.46875, 0.46875, 5.0001044273376465),
  (0.46875, 0.46875, 5.0),
  (0.46875, 0.46875, 4.9998979568481445),
  (0.46875, 0.46875, 4.9996514320373535),
  (0.46875, 0.46875, 4.999613285064697),
  (0.46875, 0.46875, 4.9998393058776855),
  (0.46875, 0.46875, 4.999814987182617),
  (0.46875, 0.46875, 5.0),
  (0.46875, 0.46875, 4.999840259552002),
  (0.46875, 0.46875, 5.000284671783447),
  (0.46875, 0.46875, 4.999572277069092),
  (0.46875, 0.46875, 5.0),
  (0.46875, 0.46875, 4.999825954437256),
  (0.46875, 0.46875, 5.000333786010742),
  (0.46875, 0.46875, 5.17108678817749),
  (0.46875, 0.46875, 4.999644756317139),
  (0.46875, 0.46875, 4.999832630157471),
  (0.46875, 0.46875, 4.999792575836182),
  (0.46875, 0.46875, 4.999516010284424),
  (0.46875, 0.46875, 5.000307083129883),
  (0.46875, 0.46875, 4.9996137619018555),
  (0.46875, 0.46875, 5.0004425048828125),
  (0.46875, 0.46875, 5.189216613769531),
  (0.46875, 0.46875, 4.999832630157471),
  (0.46875, 0.46875, 4.999832630157471),
  (0.46875, 0.46875, 4.99970817565918),
  (0.46875, 0.46875, 4.999825954437256),
  (0.46875, 0.46875, 5.12418794631958),
  (0.46875, 0.46875, 4.999832630157471),
  (0.46875, 0.46875, 5.017246723175049),
  (0.46875, 0.46875, 4.9998650550842285),
  (0.46875, 0.46875, 5.0),
  (0.46875, 0.46875, 4.999674320220947),
  (0.46875, 0.46875, 4.999832630157471),
  (0.46875, 0.46875, 0.6248558759689331),
  (0.46875, 0.46875, 5.0),
  (0.46875, 0.46875, 5.2138590812683105),
  (0.46875, 0.46875, 4.999539852142334),
  (0.46875, 0.46875, 4.9998579025268555),
  (0.46875, 0.46875, 5.0),
  (0.46875, 0.46875, 5.026040554046631),
  (0.46875, 0.46875, 5.000058650970459),
  (0.46875, 0.46875, 4.999519348144531),
  (0.46875, 0.46875, 5.000333786010742),
  (0.46875, 0.46875, 4.999605655670166),
  (0.46875, 0.46875, 4.999519348144531),
  (0.46875, 0.46875, 5.170974254608154),
  (0.46875, 0.46875, 3.0179784297943115),
  (0.46875, 0.46875, 4.999581336975098),
  (0.46875, 0.46875, 4.999771595001221),
  (0.46875, 0.46875, 4.999581336975098),
  (0.46875, 0.46875, 4.999978542327881),
  (0.46875, 0.46875, 4.9995269775390625),
  (0.46875, 0.46875, 4.999840259552002),
  (0.46875, 0.46875, 4.999840259552002),
  (0.46875, 0.46875, 4.999833106994629),
  (0.46875, 0.46875, 4.999771595001221),
  (0.46875, 0.46875, 5.094393253326416),
  (0.46875, 0.46875, 4.99970817565918),
  (0.46875, 0.46875, 4.9995646476745605),
  (0.46875, 0.46875, 2.500372886657715),
  (0.46875, 0.46875, 4.999925136566162),
  (0.46875, 0.46875, 5.059998989105225),
  (0.46875, 0.46875, 4.999557971954346),
  (0.46875, 0.46875, 5.0004425048828125),
  (0.46875, 0.46875, 4.999832630157471),
  (0.46875, 0.46875, 5.0003485679626465),
  (0.46875, 0.46875, 4.999613285064697),
  (0.46875, 0.46875, 4.999832630157471),
  (0.46875, 0.46875, 4.999897480010986),
  (0.46875, 0.46875, 4.999613285064697),
  (0.46875, 0.46875, 5.079674243927002),
  (0.46875, 0.46875, 5.000065803527832),
  (0.46875, 0.46875, 4.999843597412109),
  (0.46875, 0.46875, 5.00040340423584),
  (0.46875, 0.46875, 5.000402927398682),
  (0.46875, 0.46875, 4.999634742736816),
  (0.46875, 0.46875, 4.999627113342285),
  (0.46875, 0.46875, 4.999927043914795),
  (0.46875, 0.46875, 4.999810218811035),
  (0.46875, 0.46875, 5.00040340423584),
  (0.46875, 0.46875, 5.0536088943481445),
  (0.46875, 0.46875, 4.999627113342285),
  (0.46875, 0.46875, 5.154026031494141),
  (0.46875, 0.46875, 4.999879837036133),
  (0.43945300579071045, 0.43945300579071045, 5.000471115112305),
  (0.4882810115814209, 0.4882810115814209, 5.0004425048828125),
  (0.4492189884185791, 0.4492189884185791, 4.999832630157471),
  (0.4882810115814209, 0.4882810115814209, 4.9998650550842285),
  (0.4882810115814209, 0.4882810115814209, 4.999516010284424),
  (0.4882810115814209, 0.4882810115814209, 4.999516010284424),
  (0.3984380066394806, 0.3984380066394806, 5.000471591949463),
  (0.5, 0.5, 4.999832630157471),
  (0.44335898756980896, 0.44335898756980896, 5.000464916229248),
  (0.4257810115814209, 0.4257810115814209, 5.000281810760498),
  (0.37304699420928955, 0.37304699420928955, 5.000457763671875),
  (0.4414060115814209, 0.4414060115814209, 4.999792575836182),
  (0.46875, 0.46875, 5.000142574310303),
  (0.46875, 0.46875, 5.0),
  (0.46875, 0.46875, 5.0),
  (0.41015625, 0.41015625, 4.996953964233398),
  (0.46875, 0.46875, 4.999832630157471),
  (0.4680851101875305, 0.4680851101875305, 4.567727565765381),
  (0.46875, 0.46875, 4.9998650550842285),
  (0.46875, 0.46875, 5.0),
  (0.46875, 0.46875, 4.999832630157471),
  (0.46875, 0.46875, 5.000281810760498),
  (0.46875, 0.46875, 5.000288963317871),
  (0.46875, 0.46875, 4.999843597412109),
  (0.46875, 0.46875, 5.000411033630371),
  (0.46875, 0.46875, 5.000411033630371),
  (0.46875, 0.46875, 5.00040340423584),
  (0.46875, 0.46875, 5.124475002288818),
  (0.46875, 0.46875, 4.999516010284424),
  (0.46875, 0.46875, 4.999660015106201),
  (0.46875, 0.46875, 5.0),
  (0.46875, 0.46875, 4.999565124511719),
  (0.46875, 0.46875, 5.0002593994140625),
  (0.46875, 0.46875, 4.999832630157471),
  (0.46875, 0.46875, 4.999870300292969),
  (0.46875, 0.46875, 4.829629421234131),
  (0.4882810115814209, 0.4882810115814209, 5.000242233276367),
  (0.46875, 0.46875, 4.9995574951171875),
  (0.4296880066394806, 0.4296880066394806, 5.0),
  (0.46875, 0.46875, 4.999840259552002),
  (0.46875, 0.46875, 4.999833106994629),
  (0.46875, 0.46875, 4.924038887023926),
  (0.46875, 0.46875, 4.999613285064697),
  (0.46875, 0.46875, 4.999905109405518),
  (0.46875, 0.46875, 4.999693870544434),
  (0.46875, 0.46875, 4.999627113342285),
  (0.46875, 0.46875, 4.999825954437256),
  (0.46875, 0.46875, 4.727592945098877),
  (0.46875, 0.46875, 4.999825954437256),
  (0.46875, 0.46875, 4.999832630157471),
  (0.46875, 0.46875, 4.999565124511719),
  (0.46875, 0.46875, 4.999832630157471),

In [ ]:
df = pd.DataFrame(data=tags)
display(df.head(5))

  Dirección del estudio  spacing  n_slices
0        sub-stroke0001      2.0        75
1        sub-stroke0002      2.0        75
2        sub-stroke0003      2.0        70
3        sub-stroke0004      2.0        69
4        sub-stroke0005      2.0        69

In [17]:
df.describe()

          spacing    n_slices
count  149.000000  149.000000
mean     2.535569   64.973154
std      0.899327   17.839353
min      0.800000   34.000000
25%      2.000000   46.000000
50%      2.000000   69.000000
75%      3.999987   74.000000
max      4.000012  177.000000

In [ ]:
df.to_excel("MetadatosNIfTI.xlsx")